# -*- coding: utf-8 -*-
"""BenjaminsPenguinsM3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIV0W4nfSWLP8Sryea_gtn6-PNuBuFkN
"""

from ast import In
# PalmerPenguinsM3.py
# Benjamin Watson
# 10/5/2026
# Uses lists and formatted output to analyze Palmer Penguin statistics.

import math
# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

total_penguins = NUM_CHINSTRAP + NUM_GENTOO + NUM_ADELIE
average_penguins = total_penguins / TOTAL_SPECIES
# what percent of the total penguins each species has
chinstrap_percent = (NUM_CHINSTRAP / total_penguins) * 100
gentoo_percent = (NUM_GENTOO / total_penguins) * 100
adelie_percent = (NUM_ADELIE / total_penguins) * 100

average_penguins_rounded_up = math.ceil(average_penguins)

# output species name with intro text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()
print("There area total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")
# more census data about the species
print("There is a total of", total_penguins, "penguins.")
# Lists about the penguins
species_names = [SP_CHINSTRAP, SP_GENTOO, SP_ADELIE]


species_counts = [NUM_CHINSTRAP, NUM_GENTOO, NUM_ADELIE]


total_species = len(species_names)
total_penguins = sum(species_counts)
average_penguins = total_penguins / total_species
average_penguins_rounded_up = math.ceil(average_penguins)

chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

largest_count = max(species_counts)
smallest_count = min(species_counts)

largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)

largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]
# More data about the penguins
print(f"The average number of penguins per species is "
      f"{average_penguins:.1f}.\n")
print(f"{species_names[0]}: {species_counts[0]} "
      f"({chinstrap_percent:.2f}%)")
print(f"{species_names[1]}: {species_counts[1]} "
      f"({gentoo_percent:.2f}%)")
print(f"{species_names[2]}: {species_counts[2]} "
      f"({adelie_percent:.2f}%)\n")
print(f"The species with the most observations is {species_names[2]} with {species_counts[2]} penguins.")
print(f"The species with the least observations is {species_names[0]} with {species_counts[0]} penguins.")