# -*- coding: utf-8 -*-
"""Benjamins Penguins

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIV0W4nfSWLP8Sryea_gtn6-PNuBuFkN
"""

# PalmerPenguins.py
# Benjamin Watson
# 9/28/2026
# Introduces the Palmer Penguin Species

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

# output species name with intro text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()
print("There area total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")