# -*- coding: utf-8 -*-
"""BenjaminsPenguinsM2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIV0W4nfSWLP8Sryea_gtn6-PNuBuFkN
"""

# PalmerPenguinsM2.py
# Benjamin Watson
# 10/5/2026
# Calculates and displays Palmer Penguin statistics.

import math
# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

total_penguins = NUM_CHINSTRAP + NUM_GENTOO + NUM_ADELIE
average_penguins = total_penguins / TOTAL_SPECIES
# what percent of the total penguins each species has
chinstrap_percent = (NUM_CHINSTRAP / total_penguins) * 100
gentoo_percent = (NUM_GENTOO / total_penguins) * 100
adelie_percent = (NUM_ADELIE / total_penguins) * 100

average_penguins_rounded_up = math.ceil(average_penguins)

# output species name with intro text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()
print("There area total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")
# more census data about the species
print("There is a total of", total_penguins, "penguins.")
print("The average number of penguins per species is", average_penguins_rounded_up, ".")
print(SP_CHINSTRAP + ": " + str(chinstrap_percent) + "%")
print(SP_GENTOO + ": " + str(gentoo_percent) + "%")
print(SP_ADELIE + ": " + str(adelie_percent) + "%")